name: Unzip Gede

on:
  workflow_dispatch:
    inputs:
      url_zip:
        description: 'URL file ZIP nya'
        required: true

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Download & Extract
        run: |
          wget -O file.zip "${{ inputs.url_zip }}"
          unzip -o file.zip
          rm file.zip
          
      - name: Upload hasil
        uses: actions/upload-artifact@v4
        with:
          name: hasil-ekstrak
          path: ./*
